---

- name: MySQL check for icingaweb db schema
  ansible.builtin.shell: >
    {{ _tmp_mysqlcmd }}
    -Ns -e "select * from icingaweb_user" ||
    (
      {{ _tmp_mysqlcmd }} < /usr/share/icingaweb2/schema/mysql.schema.sql &&
      echo "Schema imported"
    )
  register: _icingaweb_schema
  changed_when:
    - '"Schema imported" in _icingaweb_schema.stdout_lines'
  throttle: 1

