minor_changes:
  - Add the `Performance Data Graphs Prometheus module <https://github.com/NETWAYS/icingaweb2-module-perfdatagraphs-prometheus>`__ to the :code:`icingaweb2` role.
  - Add :code:`prometheus` to the :code:`default_backend` choices for the :code:`perfdatagraphs` module.
