---
- name: Prepare
  hosts: all
  tasks:
    - name: Install requirements for Debian
      apt:
        name:
          - gpg
          - apt-transport-https
          - python3-debian
        update_cache: yes
      when: ansible_os_family == "Debian"
