---
- name: Debian - Install Icinga Web 2 packages
  ansible.builtin.apt:
    name: "{{ icingaweb2_packages + icingaweb2_packages_dependencies }}"
    state: present
    update_cache: true

# 'name' accepts a list as of community.general 9.3.0.
- name: Debian - Install requested locales
  when: icingaweb2_locales | length > 0
  community.general.locale_gen:
    state: present
    # Append the encoding, e.g. 'de_DE' -> 'de_DE.UTF-8'
    name: "{{ icingaweb2_locales | unique | map('regex_replace', '^(.+)$', '\\1.UTF-8') }}"
