- name: Set permissions on icingaweb config
  ansible.builtin.file:
    state: directory
    dest: "{{ icingaweb2_config_dir }}"
    owner: "{{ icingaweb2_httpd_user }}"
    group: "{{ icingaweb2_group }}"
    mode: "2770"

- name: Set permissions on enabledModules
  ansible.builtin.file:
    state: directory
    dest: "{{ icingaweb2_config_dir }}/enabledModules"
    owner: "{{ icingaweb2_httpd_user }}"
    group: "{{ icingaweb2_group }}"
    mode: "2770"

- name: Set permissions on modules
  ansible.builtin.file:
    state: directory
    dest: "{{ icingaweb2_config_dir }}/modules"
    owner: "{{ icingaweb2_httpd_user }}"
    group: "{{ icingaweb2_group }}"
    mode: "2770"

- name: Ensure fragments exists
  ansible.builtin.file:
    state: directory
    dest: "{{ icingaweb2_fragments_path }}/{{ item }}"
    owner: root
    group: "{{ icingaweb2_group }}"
  loop:
    - resources
    - authentication
    - roles

- name: Create icingaweb2 config files
  ansible.builtin.template:
    src: "modules_config.ini.j2"
    dest: "{{ icingaweb2_config_dir }}/{{ item }}.ini"
    owner: "{{ icingaweb2_httpd_user }}"
    group: "{{ icingaweb2_group }}"
    mode: "0660"
  loop:
    - config
    - authentication
    - groups
  vars:
    _i2_config_hash: "{{ lookup('ansible.builtin.vars', 'icingaweb2_' + item) }}"

- name: Create temporary config variable
  ansible.builtin.set_fact:
    _tmp_i2_config_hash:
      roles: {}
      resources: {}

- name: Prepare config hash
  when: icingaweb2_db is defined
  vars:
    _resources:
      icingaweb2_db:
        type: db
        db: "{{ icingaweb2_db['type'] | default('mysql') }}"
        host: "{{ icingaweb2_db['host'] }}"
        port: "{{ icingaweb2_db['port'] | default(omit) }}"
        dbname: "{{ icingaweb2_db['name'] }}"
        username: "{{ icingaweb2_db['user'] }}"
        password: "{{ icingaweb2_db['password'] }}"
        charset: "{{ icingaweb2_db['charset'] | default(omit) }}"
        use_ssl: "{{ '1' if icingaweb2_db['ssl_cert'] is defined else '0' }}"
        ssl_cert: "{{ icingaweb2_db['ssl_cert'] | default(omit) }}"
        ssl_key: "{{ icingaweb2_db['ssl_key'] | default(omit) }}"
        ssl_ca: "{{ icingaweb2_db['ssl_ca'] | default(omit) }}"
        ssl_cipher: "{{ icingaweb2_db['ssl_cipher'] | default(omit) }}"
        ssl_capath: "{{ icingaweb2_db['ssl_capath'] | default(omit) }}"
  ansible.builtin.set_fact:
    _tmp_i2_config_hash: "{{ _tmp_i2_config_hash | combine({'resources': _resources}, recursive=true) }}"

- name: Set resources facts
  when: icingaweb2_resources is defined
  ansible.builtin.set_fact:
    _tmp_i2_config_hash: "{{ _tmp_i2_config_hash | combine({'resources': icingaweb2_resources}, recursive=true) }}"

- name: Assemble roles.ini (adding default admin role)
  when: icingaweb2_admin_username is defined and icingaweb2_admin_password is defined
  vars:
    _tmp_i2_config_hash_admin_role:
      default_admins:
        users:
          - "{{ icingaweb2_admin_username }}"
        permissions:
          - "*"
  ansible.builtin.set_fact:
    _tmp_i2_config_hash: "{{ _tmp_i2_config_hash | combine({'roles': _tmp_i2_config_hash_admin_role}, recursive=true) }}"

- name: Assemble roles.ini (adding icingaweb2_roles)
  when: icingaweb2_roles is defined
  ansible.builtin.set_fact:
    _tmp_i2_config_hash: "{{ _tmp_i2_config_hash | combine({'roles': icingaweb2_roles}, recursive=true) }}"

- name: Deploy configuration files
  loop: "{{ _tmp_i2_config_hash | dict2items }}"
  vars:
    _i2_config_hash: "{{ _tmp_i2_config_hash[item.key] }}"
  ansible.builtin.template:
    src: modules_config.ini.j2
    dest: "{{ icingaweb2_config_dir }}/{{ item.key }}.ini"
    group: "{{ icingaweb2_group }}"
    owner: "{{ icingaweb2_httpd_user }}"
    mode: "0660"
