---
- name: PgSQL import IcingaDB schema
  when: icingadb_database_import_schema| default(False)
  block:
    - name: Build pgsql command
      ansible.builtin.set_fact:
        _tmp_pgsqlcmd: >-
          PGPASSWORD={{ icingadb_database_password | quote }}
          psql
          "{% if icingadb_database_host %} host="{{ icingadb_database_host }}" {%- endif %}
          {% if icingadb_database_port is defined %} port={{ icingadb_database_port }} {%- endif %}
          user={{ icingadb_database_user | default('icingadb') }}
          dbname={{ icingadb_database_name | default('icingadb') }}
          {% if icingadb_database_sslmode is defined %} sslmode={{ icingadb_database_sslmode }} {%- endif %}
          {% if icingadb_database_ca is defined %} sslrootcert={{ icingadb_database_ca }} {%- endif %}
          {% if icingadb_database_cert is defined %} sslcert={{ icingadb_database_cert }} {%- endif %}
          {% if icingadb_database_key is defined %} sslkey={{ icingadb_database_key }} {%- endif %}
          {% if icingadb_database_ssl_extra_options is defined %} {{ icingadb_database_ssl_extra_options }} {%- endif %}"

    - name: PgSQL import IcingaDB schema
      ansible.builtin.shell: >
        {{ _tmp_pgsqlcmd }}
        -w -c "select version from icingadb_schema" ||
        (
          {{ _tmp_pgsqlcmd }} -w -f {{ icingadb_database_schema }} &&
          echo "Schema imported"
        )
      register: _icingadb_schema
      changed_when:
        - '"Schema imported" in _icingadb_schema.stdout_lines'
      throttle: 1
