---

- name: feature command ExternalCommandListener object
  ansible.builtin.set_fact:
    icinga2_objects: "{{ icinga2_objects + objects }}"
  vars:
    objects:
      - name: command
        type: ExternalCommandListener
        file: features-available/command.conf
        args: "{{ icinga2_dict_features.command }}"
