---

- name: feature command ExternalCommandListener object
  ansible.builtin.set_fact:
    tmp_objects: "{{ tmp_objects | default([]) + objects }}"
  vars:
    objects:
      - name: command
        type: ExternalCommandListener
        file: features-available/command.conf
        args: "{{ icinga2_dict_features.command }}"
