---

- name: feature graphite GraphiteWriter object
  ansible.builtin.set_fact:
    icinga2_objects: "{{ icinga2_objects + objects }}"
  vars:
    objects:
      - name: graphite
        type: GraphiteWriter
        file: features-available/graphite.conf
        args: "{{ icinga2_dict_features.graphite }}"
