---

- name: feature influxdb InfluxdbWriter object
  ansible.builtin.set_fact:
    icinga2_objects: "{{ icinga2_objects + objects }}"
  vars:
    objects:
      - name: influxdb
        type: InfluxdbWriter
        file: features-available/influxdb.conf
        args: "{{ icinga2_dict_features.influxdb }}"
